// Ori v2 — the letter quality gate.
//
// The nightly letter is L4 (interpretive) prose generated by an LLM. The
// honesty discipline forbids it from slipping into clinical/diagnostic
// territory, and the UI depends on a strict shape (headline + paragraphs
// + optional part references). This gate validates both BEFORE a letter
// is stored or shown: letterEngine retries once on failure and otherwise
// fails closed — the banner keeps saying "tonight" rather than showing
// an unvetted letter. Pure module (no DOM, no React) so the eval suite
// (scripts/eval-letter-v2.mjs) exercises the same code under Node.

// Diagnosis-shaped vocabulary the letter must never use about the user.
// Deliberately conservative: names of conditions and prescriptive medical
// language, not everyday words ("a heavy day" is fine; "you have ADHD"
// is not). Lowercase substrings, word-ish boundaries handled in scan().
export const CLINICAL_LEXICON = [
  'diagnos',        // diagnose / diagnosis / diagnostic
  'disorder',
  'clinical',
  'adhd',
  'bipolar',
  'schizo',
  'depression',
  'depressive',
  'anxiety disorder',
  'ptsd',
  'ocd',
  'insomnia',       // the condition-claim; sleep talk stays descriptive
  'prescrib',
  'medication',
  'dosage',
  'therapy you need',
  'syndrome',
  'patholog',
  'burnout',        // pop-clinical label — describe the load instead
  // Academic / physiological register. The letter PROSE rarely trips these,
  // but the model's `insights` field leaned on them ("allostatic load
  // signature", "neurobehavioral degradation") — which reads as a clinical
  // assessment, the one thing Ori promises it is not. Caught here so no
  // user-visible channel (prose, insight, or part note) can carry them.
  'allostatic',
  'neurobehavioral',
  'neurobiolog',
  'cortisol',
  'prefrontal',
  'amygdala',
  'dopamin',
  'serotonin',
  'phq-9', 'phq9',
  'gad-7', 'gad7',
  'cognitive distortion',
  'maladaptive',
  'comorbid',
  'dysregulat',
  'neural',
];

// Named-researcher citations read as a literature review, not a friend's
// noticing — "McEwen, 1998" · "Lim & Dinges (2010)" · "Walker (2017)" ·
// "et al." We match only YEAR-ANCHORED citation shapes (a parenthetical year,
// a surname directly followed by a year, or "et al") — the forms the model
// actually emits — and deliberately NOT a bare "Name and Name", which would
// misfire on a letter naming two people ("Sam and Alex talked it out").
export const CITATION_RE = /\((?:19|20)\d{2}\)|\b[A-Z][A-Za-z]+,?\s+(?:19|20)\d{2}\b|\bet\s+al\.?/;

// Prose channel (headline + paragraphs): lexicon substrings only. A hit here
// HARD-FAILS the letter, so we keep it to unambiguous tells (condition names
// + physiological/academic register). Citation-shape is intentionally NOT a
// prose hard-fail — a stray year in a friendly line ("back in 2019") shouldn't
// strand the evening's letter, and the register terms already catch the
// academic voice if it ever leaks into the body.
function scan(text) {
  const hits = [];
  const lower = String(text || '').toLowerCase();
  for (const term of CLINICAL_LEXICON) {
    if (lower.includes(term)) hits.push(term);
  }
  return hits;
}

// Academic-register tells with no year to anchor on — a named theory or an
// appeal to "research / studies" reads as a literature review, not a friend.
// "Fredrickson's broaden-and-build theory" · "Yerkes-Dodson" · "research
// shows" · "studies suggest" · "et al." Applied ONLY to the auxiliary channels
// (below), never the prose hard-fail, since a bare "theory" can be innocent
// ("my theory is the weekends are harder") and dropping one insight is cheap.
const ACADEMIC_RE = /\b(?:theory|hypothesis|paradigm|broaden-and-build|yerkes-dodson|research\s+(?:shows|suggests|finds|indicates)|studies\s+(?:show|suggest|find))\b/i;

// Auxiliary channels (insights, part notes): lexicon PLUS citation/academic
// register. These are DROPPED, not hard-failed, so the aggressive match is
// cheap — at worst it removes one auxiliary line, never a whole letter.
function clinicalHits(text) {
  const hits = scan(text);
  const raw = String(text || '');
  if (CITATION_RE.test(raw)) hits.push('citation');
  if (ACADEMIC_RE.test(raw)) hits.push('academic-register');
  return hits;
}

function isNonEmptyString(v) {
  return typeof v === 'string' && v.trim().length > 0;
}

// Drop any insight whose title or body carries clinical/citation language.
// Non-fatal by design: the insights are auxiliary, so a clinical one is
// removed (never shown) rather than failing the whole letter — the honesty
// contract is "the user never reads clinical language", and dropping it
// satisfies that without stranding the evening's letter.
export function sanitizeInsights(insights) {
  if (!Array.isArray(insights)) return [];
  return insights.filter((ins) => {
    if (!ins || typeof ins !== 'object') return false;
    return clinicalHits(`${ins.title || ''}\n${ins.body || ''}`).length === 0;
  });
}

// Validate an analysis result (the `a` returned by analyzeWithClaude).
// Returns { ok, problems, letter, insights } — `letter` is a sanitized copy
// (unknown part ids dropped, clinical part-notes stripped) and `insights` is
// the clinical-free subset. Prose (headline + paragraphs) hard-fails on any
// clinical tell; the auxiliary channels are sanitized in place.
export function validateLetter(a, { knownPartIds = null } = {}) {
  const problems = [];
  const letter = a?.letter;
  const insights = sanitizeInsights(a?.insights);

  if (!letter || typeof letter !== 'object') {
    return { ok: false, problems: ['letter missing'], letter: null, insights };
  }
  if (!isNonEmptyString(letter.headline)) {
    problems.push('headline missing or empty');
  }
  const paragraphs = Array.isArray(letter.paragraphs)
    ? letter.paragraphs.filter(isNonEmptyString)
    : [];
  if (paragraphs.length === 0) {
    problems.push('no readable paragraphs');
  }

  // Clinical-language scan across the prose the user reads. The letter BODY
  // must be pristine, so a hit here fails the gate (letterEngine retries once,
  // then falls back rather than show it).
  const readable = [letter.headline, ...paragraphs].join('\n');
  const hits = scan(readable);
  if (hits.length) {
    problems.push(`clinical language: ${hits.join(', ')}`);
  }

  // Part references must point at parts the app can render. Unknown ids
  // are dropped, not fatal — the letter text doesn't depend on them. A part
  // NOTE that carries clinical/citation language is stripped (the part still
  // renders; only its sentence is removed) — same auxiliary-channel discipline
  // as insights, so nothing clinical reaches the user even via a part blurb.
  let parts = Array.isArray(letter.parts) ? letter.parts : [];
  if (knownPartIds && parts.length) {
    const known = new Set(knownPartIds);
    parts = parts.filter((p) => p && known.has(p.id));
  }
  parts = parts.map((p) => (
    p && typeof p.note === 'string' && clinicalHits(p.note).length
      ? { ...p, note: '' }
      : p
  ));

  return {
    ok: problems.length === 0,
    problems,
    letter: { ...letter, paragraphs, parts },
    insights,
  };
}
