// Little wonders — shown one at a time while the letter is being written, so a
// longer wait reads as a pause worth sitting in rather than a flickering
// countdown. They rotate slowly (see Letter.jsx) and start at a random point in
// the pool each time, so consecutive evenings surface different ones.
//
// Curation rules, because this is a cognitive-health app and honesty is the
// whole point:
//   • Real, lesser-known findings — animal cognition + human perception &
//     behaviour. No "10% of your brain", no goldfish-memory myth.
//   • DEBUNKED pop-psych is excluded on purpose: power posing, ego depletion
//     (this project retired it — failed replication), the marshmallow test as
//     destiny, strong facial-feedback claims, social priming.
//   • Where a result is real but softer than the headline, it's hedged
//     ("may", "seem to", "appears", "about") rather than overstated.
//   • Plain language, one sentence, gentle. Wonder, not a lecture.

export const WAITING_FACTS = [
  // ── Birds ──────────────────────────────────────────────────────────────
  'Crows can recognise individual human faces, and stay wary of someone who once wronged them for years.',
  'Crows seem to teach their young which people to distrust — passing on a grudge to birds that never met you.',
  'A New Caledonian crow will bend a twig into a hook to fish grubs from bark, and save a good tool for later.',
  'Ravens can plan ahead, choosing a tool now for a reward they won’t be offered until much later.',
  'A scrub jay that stole food will quietly re-hide its own caches if it was watched while burying them.',
  'Clark’s nutcrackers bury up to 30,000 seeds in a season and recall most of the hiding spots months on.',
  'A grey parrot named Alex learned over a hundred words, and once asked what colour he was — the first animal known to ask about itself.',
  'Magpies can recognise themselves in a mirror, trying to remove a sticker they can only see in the reflection.',
  'Chickadees pack their alarm calls with detail — more “dee” notes mean a more dangerous predator.',
  'Japanese tits string calls together with a kind of grammar, where word order changes the meaning.',
  'Rooks drop stones into a tube of water to raise a floating treat within reach — the crow and the pitcher, for real.',
  'Cockatoos in Sydney learned to flip open wheelie-bin lids, and the trick spread bird to bird across the suburbs.',
  'Green herons fish with bait, dropping a feather or insect on the water to lure a fish up.',
  'Pigeons can be taught to tell a Monet from a Picasso, sorting paintings they’ve never seen by style.',
  'Lyrebirds mimic chainsaws, camera shutters and other birds so precisely they fool the originals.',
  'Keas — alpine parrots — solve puzzles in teams, and famously dismantle car wipers for what looks like sport.',
  'Owls have no room to roll their eyes, so they swivel their heads up to 270 degrees instead.',
  'Hummingbirds remember every flower they’ve visited and roughly when each will refill with nectar.',
  'Monarch butterflies migrate to a forest they’ve never seen, steering by an inner compass set to the sun.',
  'Honeyguide birds lead human honey-hunters to bees’ nests, answering a specific call passed down for generations.',

  // ── Mammals ────────────────────────────────────────────────────────────
  'Elephants appear to mourn, lingering over the bones of their dead and touching them gently with their trunks.',
  'Elephants greet each other with particular rumbles, and may call one another by individual names.',
  'Elephants are afraid of bees, so some farmers use humming beehive fences to steer them gently away from crops.',
  'Dolphins invent a signature whistle as a name, and will call out to a friend they haven’t seen in twenty years.',
  'Dolphins in Shark Bay pass a tradition mother to daughter, wearing sponges on their snouts to forage safely.',
  'Orcas keep dialects and hunting customs for generations — a culture carried entirely in sound.',
  'A dolphin can sleep one half of its brain at a time, staying half-awake to breathe and watch all night.',
  'Rats will free a trapped companion before taking a treat for themselves — and then share the treat.',
  'Tickled rats chirp with laughter at a pitch too high for us to hear, and chase the hand that tickles them.',
  'Chimpanzees beat people at a quick number-memory game, glancing once and recalling the whole layout.',
  'Wild chimps have local customs — a nut-cracking technique in one forest is unknown to the troop next door.',
  'Sea otters keep a favourite rock in a pouch of skin under one arm, reusing it for years to crack open shells.',
  'Otters sometimes hold hands while sleeping, so they don’t drift apart on the current.',
  'Squirrels will dig fake holes and mime burying a nut when they sense they’re being watched.',
  'Prairie dogs have calls detailed enough to describe a passing human’s size, shirt colour and speed.',
  'A dog’s nose is layered enough that it can, in a way, smell time — telling a morning scent from an evening one.',
  'Horses can read a human face, and remember whether you once looked at them in anger.',
  'Goats prefer a smiling face, and will gaze to a human for help when stuck — much as dogs do.',
  'Sheep can recognise and remember around fifty individual faces, sheep and human, for years.',
  'Cows form close friendships, and grow calmer — heart rate dropping — when they’re beside a friend.',
  'Pigs can learn to steer a cursor with a joystick, nudging it to a target for a reward.',
  'Vampire bats that fail to find food are fed by well-fed roost-mates who remember and repay past kindness.',
  'Naked mole-rats barely feel acid or chilli heat, and scarcely age the way other mammals do.',
  'Capuchin monkeys will reject unfair pay — handed a cucumber while a neighbour gets grapes, they throw it back.',
  'Vervet monkeys have distinct words for “eagle”, “leopard” and “snake”, each prompting a different escape.',
  'Sperm whales live in clans with their own dialects of clicks, and take turns babysitting each other’s calves.',
  'Humpback song started by one Pacific population can sweep across a whole ocean in a few years.',

  // ── Octopus, insects & other minds ─────────────────────────────────────
  'An octopus keeps most of its neurons in its arms, so each arm can taste, decide and explore on its own.',
  'Octopuses open jars, recognise individual keepers, and have been seen squirting water at ones they dislike.',
  'An octopus can change colour in a third of a second — though it is, strangely, colourblind.',
  'Cuttlefish can pass a patience test, holding out for a better meal rather than taking a lesser one now.',
  'Cuttlefish hypnotise prey with shimmering waves of colour rolling down their skin.',
  'Bees can be taught the idea of zero, ranking an empty page as “less than” one.',
  'Honeybees tell the hive where the flowers are by dancing a figure-eight that encodes direction and distance.',
  'Bumblebees will roll little wooden balls about with no reward at all — what looks a lot like play.',
  'Bees seem to recognise human faces, piecing the features together as if we were unusually large flowers.',
  'Ants rush to dig out a buried nest-mate, tugging only at the limbs that are actually trapped.',
  'Some ants teach, slowing to lead a naive nest-mate to food one step at a time.',
  'Leafcutter ants run the largest farms outside humanity, growing fungus on chewed leaves underground.',
  'A jumping spider plans a winding route to its prey, sometimes losing sight of it and still arriving.',
  'Spiders can fly, casting out silk to ride the sky’s faint electric fields for miles.',
  'Archerfish spit a jet of water to knock insects off leaves — and can tell human faces apart.',
  'Dung beetles steer by the glow of the Milky Way, the only animals known to navigate by the galaxy.',
  'Mantis shrimp see with up to sixteen kinds of colour receptor, to our three.',
  'A cleaner wrasse — a finger-sized fish — passed the mirror self-recognition test once thought to need a big brain.',
  'Frogs and toads can count, choosing the call that signals more rivals or more eggs.',
  'Tardigrades can survive boiling, freezing, drying out for decades, and even the vacuum of space.',
  'Slime moulds have no brain at all, yet can solve mazes and retrace the layout of a subway map.',
  'A wood frog can freeze almost solid all winter, its heart stopped, then thaw in spring and hop away.',
  'Axolotls can regrow a lost leg, parts of the heart, and even slices of brain.',
  'Ducklings can grasp “same” and “different”, bonding to whatever shape first fits the rule.',
  'A pistol shrimp snaps its claw so fast it briefly boils the water and stuns prey with the sound.',

  // ── How you see, hear, and sense ───────────────────────────────────────
  'Your eyes flick around several times a second, and your brain edits out the blur so the world holds still.',
  'When your gaze lands somewhere new your brain stretches that first instant — why a stopped clock’s hand seems to pause.',
  'You can’t tickle yourself, because your brain predicts your own touch and quietly cancels the surprise.',
  'Smell is wired almost straight into memory, which is why a single scent can throw you back decades.',
  'Your brain is about two percent of your weight but burns roughly a fifth of your energy, awake or asleep.',
  'Watch lips say “ga” while a voice says “ba”, and you’ll hear a third sound — you listen partly with your eyes.',
  'Your nose is always in view at the edge of sight; your brain simply edits it out until you notice it.',
  'Your brain quietly fills in your blind spot — where the optic nerve leaves the eye — with a best guess.',
  'Colour isn’t out in the world; it’s your brain’s reading of wavelengths, painted onto what you see.',
  'Your two eyes send slightly different pictures, and your brain fuses them into one, inventing the depth.',
  'Reading, your eyes don’t glide — they jump and stop, and you only see sharply during the stops.',
  'You have a quiet sixth sense, proprioception: eyes shut, you still know exactly where your hand is.',
  'Leave a gap in a familiar tune and your brain supplies the missing note, as if you’d heard it.',
  'Faces appear in clouds, sockets and burnt toast because the brain is tuned to find them everywhere.',
  'As daylight fades, reds darken first and blues seem to glow — the world’s palette shifts at dusk.',
  'You can often hear the difference between hot and cold water being poured, from the pitch alone.',
  'A scent fades from notice within minutes as your nose simply stops reporting it.',
  'You blink fifteen to twenty times a minute, and barely notice the world going briefly dark each time.',
  'When you concentrate hard you blink less, your eyes waiting for a lull in the action.',
  'The number of things you can hold in mind at once is famously small — closer to four than seven.',
  'A surprising number of people, told to count passes in a game, miss a person in a gorilla suit walking through.',
  'We’re poor at spotting a change in a scene if it happens during a blink or a cut.',
  'The “ten percent of the brain” line is a myth — you use nearly all of it, just not all at once.',
  'Your gut has its own dense web of neurons, sometimes called a second brain.',
  'Strong emotion stamps a memory deeper, which is why you recall just where you were for big news.',

  // ── How memory, sleep, and the mind work ───────────────────────────────
  'Memory isn’t a recording — each time you recall something, you rewrite it a little.',
  'We keep the gist and the feeling of a day far longer than its details.',
  'The “tip of the tongue” feeling is your brain finding a word’s shape and meaning before its sound.',
  'In a noisy room you can’t follow two voices at once, yet your own name across it still snaps your attention.',
  'Some people have no mind’s eye at all and can’t picture an apple; others see it in vivid colour.',
  'A handful of people can recall almost every day of their lives, down to the weather.',
  'Sleep doesn’t just rest the brain — it files the day, replaying and sorting what you learned.',
  'A brief brush with light sleep can hand you a solution that eluded you wide awake.',
  'Time feels faster as we age, partly because each year is a smaller slice of all you’ve lived.',
  'Novelty stretches time: a trip full of new things feels long in memory, a routine week vanishes.',
  'Your sense of “now” lags reality by a fraction of a second — you live slightly in the past.',
  'Your brain is forever predicting the next moment; surprise is just a prediction that missed.',
  'Naming a feeling — simply putting it into words — measurably loosens its grip on you.',
  'Writing a worry down by hand tends to ease it more than turning it over and over in your head.',
  'We forecast our feelings poorly: bad events tend to hurt less, and good ones thrill less, than we expect.',
  'We adapt fast to fortune good and bad alike; most big changes fade back toward our old baseline.',
  'Awe — a canyon, a night sky — can make time feel slower and people a little more generous.',
  'Goosebumps are a leftover reflex from furrier ancestors, your skin trying to fluff up fur you no longer have.',
  'That shiver down the spine from music comes with a real release of dopamine, the brain’s reward chemical.',
  'Loneliness and physical pain share brain circuitry, which is why being left out can genuinely ache.',

  // ── How we read each other ─────────────────────────────────────────────
  'Do someone a small favour and you’ll tend to like them more — your mind decides you must have cared.',
  'We remember unfinished tasks better than finished ones; an open loop keeps a quiet tab running.',
  'The more often you meet a face, a word or a tune, the more you tend to like it — familiarity warms us.',
  'We judge a whole experience mostly by its peak and its ending, not by its average.',
  'Start noticing a word and you’ll suddenly see it everywhere — the world didn’t change, your filter did.',
  'We like the letters in our own name a little more than the rest, and even favour our birthday’s numbers.',
  'A small, human stumble can make a capable person more likeable, not less.',
  'People quietly mirror the posture and gestures of those they’re warming to.',
  'Tell a vivid story about someone else’s traits, and listeners quietly attach those traits to you.',
  'We assume others notice our slip-ups far more than they really do.',
  'Yawns are catching, and the more empathy you feel for someone, the more easily their yawn pulls one from you.',
  'Emotions spread through a group like weather; sit among calm people and you tend to calm too.',
  'We tend to like people more after we’ve opened up to them — and they to us.',
  'Humans show a lot of white in their eyes, which makes it easy to follow exactly where someone is looking.',
  'A genuine smile reaches the eyes, and we can usually feel the difference even when we can’t name it.',
  'Sharing good news with someone who truly celebrates it deepens the bond more than the news itself.',
  'People reliably underestimate how much a kind word will mean to the person who receives it.',
  'Simply being listened to, without being fixed, lowers a person’s stress and clears their thinking.',
  'We sync without meaning to — falling into step, breathing together, even matching heartbeats in a choir.',
  'Six-month-olds already tend to prefer a helpful character over a hindering one in a little puppet show.',

  // ── Small wonders ──────────────────────────────────────────────────────
  'Salmon find their way home by the unique smell of their birth stream, learned as fry years before.',
  'Beavers build to the sound of running water; play them a recording and they’ll try to dam a dry wall.',
  'A blue whale’s heart is roughly the size of a small car, and its beat can be detected from far off.',
  'Crows have been filmed sliding down snowy roofs on bottle lids, seemingly just for the fun of it.',
  'Spending on experiences tends to bring more lasting joy than spending on things.',
  'Acts of kindness lift the giver’s mood more reliably than spending the same on themselves.',
  'A short walk in nature, even a brief one, measurably steadies attention and mood.',
  'We tend to be happier when our attention rests on what we’re doing than when the mind wanders off.',
  'People who jot down what they’re grateful for tend to sleep a little better and feel more hopeful.',
  'Music with no words can move us to tears by setting up a pattern and then gently breaking it.',
  'Pour a glass of wine dyed red and tasters will describe it in the language of reds, fooled by the colour.',
  'We feel a loss about twice as keenly as we feel an equal gain.',
  'The future feels oddly faint; we’ll often take a little now over a lot later, then wish we hadn’t.',
  'Most people can sustain around 150 stable relationships — a number that turns up from villages to address books.',
  'Babies seem to hear and remember music from the womb, settling to a tune they knew before birth.',
];
